---
- name:
  hosts: all

  tasks:
    - name: Install required packages
      yum:
        name: policycoreutils-python-utils
        state: present

    - name: create the test file
      file:
        name: /tmp/selinux
        state: touch
    
    - name: set selinux context
      sefcontext:
        target: /tmp/selinux
        setype: httpd_sys_content_t
        state: present
      notify:
        - run restorecon

  handlers:
   - name: run restorecon
     command: restorecon -v /tmp/selinux


