---
- name: Conditionals test
  hosts: dev

  tasks:
    - name: Update the kernel if suff space
      package:
        name: kernel
        state: latest
      loop: "{{ ansible_facts['mounts'] }}"
      when: item.mount == "/boot" and item.size_available > 20000000
