---
- hosts: ansible1
  become: true
  become_method: sudo
  become_user: root
  vars:
    # Use "targeted" SELinux policy type
    selinux_policy: targeted
    # Set "enforcing" mode
    selinux_state: enforcing
    # Switch some SELinux booleans
    selinux_fcontexts:
      - { target: '/var/ftp(/.*)?', setype: 'public_content_rw_t', ftype: 'd' }
    # Restore SELinux file contexts in '/var/ftp/uploads'
    selinux_restore_dirs:
      - /var/ftp/uploads
    # Map tcp port 82 to the 'http_port_t' SELinux port type
    selinux_ports:
      - { ports: '82', proto: 'tcp', setype: 'http_port_t', state: 'present' }
  tasks:
    - name: Creates directory
      file:
        path: /var/ftp/uploads
        state: directory
        setype: public_content_rw_t
        mode: "0777"

    - name: execute the role and catch errors
      block:
        - name: Include selinux role
          include_role:
            name: rhel-system-roles.selinux
      rescue:
        # Fail if failed for a different reason than selinux_reboot_required.
        - name: handle errors
          fail:
            msg: "role failed"
          when: not selinux_reboot_required

        - name: restart managed host
          reboot:

        - name: wait for managed host to come back
          wait_for_connection:
            delay: 10
            timeout: 300

        - name: reapply the role
          include_role:
            name: rhel-system-roles.selinux
