---
- name: Testing conditionals
  hosts: all

  tasks: 

    - name: Install if the distribution is RedHat
      yum:
        name: httpd
        state: present
      #loop: "{{ ansible_facts['mounts'] }}"
      when: 
        ( ansible_facts['distribution'] == "CentOS")   
    
           
